<?php

/**
 * @file
 *
 * Install, update and uninstall functions for the Honeypot module.
 */

/**
 * Implements hook_update_N().
 */
function honeypot_update_7001() {
  $ret = array();

  // Leaving this in because I had it in version 1.3. Silly me.

  return $ret;
}

/**
 * Implements hook_uninstall().
 */
function honeypot_uninstall() {
  db_delete('variable')
    ->condition('name', db_like('honeypot_') . '%', 'LIKE')
    ->execute();
  $cache_tables = array('variables', 'cache_bootstrap');
  foreach ($cache_tables as $table) {
    if (db_table_exists($table)) {
      cache_clear_all($table, 'cache');
    }
  }
}
