<?php

/**
 * @file
 *
 * Install, update and uninstall functions for the Honeypot module.
 */

/**
 * Implements hook_update_N().
 */
function honeypot_update_7001() {
  // Grant administrator the 'bypass honeypot protection' permission.
  permissions_grant_permissions('administrator', array('bypass honeypot protection'));
}

/**
 * Implements hook_uninstall().
 */
function honeypot_uninstall() {
  db_delete('variable')
    ->condition('name', db_like('honeypot_') . '%', 'LIKE')
    ->execute();
  cache_clear_all('variables', 'cache_bootstrap');
}
