<?php

/**
 * @file
 *
 * Install, update and uninstall functions for the Honeypot module.
 */

/**
 * Implements hook_install().
 */
function honeypot_install() {
  drupal_set_message(t("Honeypot installed successfully. Please !link to protect your forms from spam bots.", array(
    '!link' => l(t('configure Honeypot'), 'admin/settings/honeypot')
  )));
}

/**
 * Implements hook_uninstall().
 */
function honeypot_uninstall() {
  db_query("DELETE from {variable} WHERE name LIKE 'honeypot_%'");
  $cache_tables = array('variables', 'cache_bootstrap');
  foreach ($cache_tables as $table) {
    if (db_table_exists($table)) {
      cache_clear_all($table, 'cache');
    }
  }
}

/**
 * Update Honeypot user registration form variable.
 */
function honeypot_update_6100() {
  // Get the existing value of the user registration form protection.
  $user_registration_form_value = variable_get('honeypot_form_user_register_form', 0);
  // Delete the old variable.
  variable_del('honeypot_form_user_register_form');
  // Create a new variable with the value from the old variable.
  variable_set('honeypot_form_user_register', $user_registration_form_value);
  // Must at least return an empty array to prevent errors.
  return array();
}
